### ISSUE TITLE
Errors shown in VScode that seems wrong and doesn't show up when compiling

### ISSUE THREAD

**Issue by tru** [MaskRay/ccls#546]
### Observed behavior

We are trying to get ccls to work on our (somewhat) messy and complicated C++ code-base. We have it indexing and mostly working but we get some strange error hints in VSCode that stands out and I can't figure out where they come from:

To take one we can look at this line of code:

`int mediaBitrate = media->get(PLEX_ATTRIBUTE_BITRATE, 0);`

which tells us:

```
no matching member function for call to 'get'ccls(2)
PropertyContainer.h(42, 23): candidate function template not viable: no known conversion from 'PlexMedia' to 'PropertyContainer' for object argument
PropertyContainer.h(30, 8): candidate function not viable: no known conversion from 'PlexMedia' to 'PropertyContainer' for object argument
PropertyContainer.h(51, 26): candidate template ignored: could not match 'T *' against 'int'
PropertyContainer.h(32, 10): candidate function not viable: requires single argument 'name', but 2 arguments were provided
```

Via various inheritances this is the method that should be called:

```
template<class T> T get(const string& name, const T& defaultValue=T())
```

This of course builds just fine and I can copy and paste the line from ccls.log and don't see any errors (after I add back the arguments to include our PCH).

We build ccls with llvm 8.0.1 since this is what we use to build the application. One developer said that the error seemed to have gone away when he built ccls locally against llvm 9. Is there something that was made better in upstream versions and we should just upgrade?

Does it matter much if the version of llvm ccls is linked to differs from the compiler we use?

### Expected behavior

Not an error on this line.

### System information

* ccls version (`git describe --tags --long`): cef02034841294f0ae1495684048677832878fa4
* clang version: 8.0.1
* OS: Linux and macOS behaves the same way
* Editor: VSCode 1.41.0
* Language client (and version): vscode-ccls 0.1.28

**Comment by tru** [comment]
Did a test with LLVM 9.0.1-rc3 and I still see the same problem.

**Comment by tru** [comment]
I tested the same file in clangd and it seems to work just fine there. Just as a reference point.

**Comment by gbooker** [comment]
I am the "one developer" mentioned above:

I should clarify that the ccls I'm using isn't technically locally built but rather the one that's installed via homebrew on the mac.  I've discovered that when I installed ccls via homebrew, I have to pin the llvm to the the version available at the same time the ccls package was built otherwise I get errors like the above.  My ccls via homebrew is [`0.20190823.3`](https://github.com/Homebrew/homebrew-core/blob/da5be93c871a99fb4e69dd47be67a41fa722d376/Formula/ccls.rb) and my llvm is [`9.0.0`](https://github.com/Homebrew/homebrew-core/blob/816c4aa526/Formula/llvm.rb) (brew's versioning).  Back when ccls was built against llvm 8, I had to pin my llvm to that version.  I recall that the brew's version `8.0.0_1` of llvm broke it back then.  Notice that the link I provided for my current llvm version in brew is **not** the same as what's currently in master; this is what I pinned it to.

With the above error, there may need to be more information in explaining a few of the other diagnostic messages is there:
- `media` is a `std::shared_ptr<PlexMedia>`
- `PlexMedia` is a subclass of a subclass of `PropertyContainer`
- `PropertyContainer` also has the methods:
  - `bool get(const string& name, string* value);`
  - `string get(const string& name)`
  - `template<class T> bool get(const string& name, T* value)`
- The aforementioned `template<class T> T get(const string& name, const T& defaultValue=T())` function is the method actually being called here and llvm builds that code using this function.

We ship to our developers the same build of llvm so we all have the same tooling on all our platforms (except Windows) and we'd like to do the same with ccls.

**Comment by MaskRay** [comment]
You may need to ensure clang command line ccls uses to parse the file is similar to the one your build system compiles the file. At least important preprocessor flags should be the same: `-D`, `-I`, `-isystem`, etc.

`--log-file=/tmp/ccls.log -v=1` dumps the clang command line. https://github.com/MaskRay/ccls/wiki/Debugging#logs

**Comment by gbooker** [comment]
I've come up with a smaller reproduction of one of the false diagnostics:
SRM.cpp:
```
#include "SRM.h"

SRM::SRM()
{
  EventManager::Get().registerSink(EVENT_PREFERENCE_MODIFIED, this);
}
```

This will result in a false diagnostic on `this` where it complains `cannot initialize a parameter of type 'IEventSink *' with an rvalue of type 'SRM *'`, but `SRM` is a subclass of `IEventSink` (hence a false diagnostic).

However, if I add to the top of `SRM.cpp`, `#include "StdAfx.h"`, then this diagnostic goes away.  `StdAfx.h` is the header we precompile, and the `compile_commands.json` contains `-include-pch -Xclang /…/cmake_pch.hxx.pch` (full path elided for brevity).  This file exists and is the pre-compiled header for `StdAfx.h`  This header includes quite a few additional headers of which some are also included by including `SRM.h`.

Additionally, if I included the contents of `SRM.h` wholesale instead of the `#include "SRM.h"`, this also resolves the false diagnostic without the `#include "StdAfx.h"`.

The PCH was compiled with the same llvm against which ccls was built and ccls is pointing at this llvm via `ccls.clang.resourceDir` in vscode.

Insertion of the `#include "StdAfx.h"` also resolved the false diagnostic in my last comment but that ends up being a more complex test case.

**Comment by david-come-pix4d** [comment]
I've the same kind of issue with gcc on the code base I work on. I've just tried with ccls and system's clang, and ccls+downloaded binary.

**Comment by MaskRay** [comment]
This was likely due to `-include-pch`. The clang executable and the clang lib ccls linked against were of different versions. Clang PCH does not have good compatibility. Somtimes you can even observer a crash. Likely fixed by https://github.com/MaskRay/ccls/pull/651

Droping `-include-pch` should work as well.

**Comment by gbooker** [comment]
> The clang executable and the clang lib ccls linked against were of different versions.

No, they are the same versions as I stated earlier:
> The PCH was compiled with the same llvm against which ccls was built and ccls is pointing at this llvm via `ccls.clang.resourceDir` in vscode.

Furthermore, if the `compile_command.json` is changed such that `-include-pch -Xclang /…/cmake_pch.hxx.pch` is replaced with `-include -Xclang ../StdAfx.h` (again, `cmake_pch.hxx.pch` is generated from `../StdAfx.h`), the false diagnostics still appear.  So this isn't a PCH issue.

In fact, we've tried a whole host of ccls builds across MacOS, Windows, and Linux and all but one produce the false diagnostics.  The only one that doesn't is ccls installed via homebrew (MacOS) and even then it only produces true diagnostics when the llvm installed via brew is pinned to specific versions (usually the llvm present in brew at the time that ccls was last updated).  This version does require the `compile_command.json` change mentioned earlier

On the other hand, clangd is getting better with only its vscode extension lagging behind ccls'.  Realistically the only thing I miss in using clangd over ccls is the rainbow highlighting.

**Comment by MaskRay** [comment]
I appreciate that you provided some details in `https://github.com/MaskRay/ccls/issues/546#issuecomment-567186976` but as you can guess it is still far from enough for troubleshooting. If a reproduced example cannot be obtained, it is difficult for an external person to help. 

> On the other hand, clangd is getting better with only its vscode extension lagging behind ccls'. Realistically the only thing I miss in using clangd over ccls is the rainbow highlighting.

I am indifferent about this statement. Honestly I don't get anything by having more users. I did not even argue when people compared cquery vs clangd once on cfe-dev. (There is some competition and clangd is embraced/supported by companies...)  To be more constructive, I'd like to see information more than "clangd is in-tree and canonical so we use it". clangd's index strategy is still inadequate to me. Having input from your perspective about (what features will be great to have in ccls) will be helpful.

-----

Something more on-topic. You can use `-include ../StdAfx.h` or `-Xclang -include -Xclang b/c.h`, but not `-include b/c.h`
I doubt the reported issue is really a ccls side thing. If you are still willing to debug, https://github.com/MaskRay/ccls/wiki/Debugging make a small change to src/sema_manager.cc:480

```
- if (in_preamble) {
+ if (0) {
```
```

and see what will happen. Setting a breakpoing on `HandleDiagnostic` will help as well.

**Comment by gbooker** [comment]
> I appreciate that you provided some details in `https://github.com/MaskRay/ccls/issues/546#issuecomment-567186976` but as you can guess it is still far from enough for troubleshooting. If a reproduced example cannot be obtained, it is difficult for an external person to help.

I know how this can be difficult without a reproduction but I and @tru did try to at least eliminate the usual suspects such as the different clang versions before you speculated that it was a cause.  I have tried to distill the issue down to something that can be shared but unfortunately it appears the complexity of the includes as well as their contents is necessary to induce the false diagnostics from ccls.

Unfortunately it seems that ccls is quite difficult to get working in our use case because we've not been able to build it on any platform without it yielding false diagnostics.  It seems there is something special about the way that homebrew builds it that we've not bee able to replicate.  Even then, when they rebuild `llvm` (not even a patch version update, just a new build), it tends to break the `ccls` package they had previously built.

> > On the other hand, clangd is getting better with only its vscode extension lagging behind ccls'. Realistically the only thing I miss in using clangd over ccls is the rainbow highlighting.
> 
> I am indifferent about this statement. Honestly I don't get anything by having more users.

This comment wasn't directed at you as much as it was directed at others who encounter this GHI to inform them of a possible alternative which may fit their needs if they are encountering the same issue.  This is also my thoughts in looking to the future where I might switch to Linux and thus off the only platform where any of us have gotten ccls no to give false diagnostics.

> Something more on-topic. You can use `-include ../StdAfx.h` or `-Xclang -include -Xclang b/c.h`, but not `-include b/c.h`

Before going down a debugging route, can you clarify the difference between `-include ../StdAfx.h` and `-include b/c.h`?  Is there something missing (such as an `-Xclang`) from one of those?
